In [4]:
import cv2
import numpy as np

image = cv2.imread('images/input.jpg')

M = np.ones(image.shape, dtype='uint8') * 75

added = cv2.add(image, M)
cv2.imshow('Brightened Image', added)

subtracted = cv2.subtract(image, M)
cv2.imshow('Substarcted Image', subtracted)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
M = np.ones(image.shape, dtype='uint8') * 75
print(M)

[[[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 ...

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]]
